development:
  access_key_id: AKIAJDRANJLHHDSFC5RA
  secret_access_key: 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

test:
  access_key_id: AKIAJDRANJLHHDSFC5RA
  secret_access_key: 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

production:
  access_key_id: AKIAJDRANJLHHDSFC5RA
  secret_access_key: 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
